apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-file-storage-pvc-1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 10Gi
